# Copyright 2018 Toyota Research Institute.  All rights reserved.

uint8  TEST_MOTOR_FRONT_LEFT = 0
uint8  TEST_MOTOR_FRONT_RIGHT = 1
uint8  TEST_MOTOR_REAR_LEFT = 2
uint8  TEST_MOTOR_REAR_RIGHT = 3

uint8  test_motor        # One of the above enum
int16  test_motor_power  # The motor PWM power to use; between -1000 and 1000
uint32 test_duration_ms  # How long to run the test for in milliseconds
---
bool    success          # Whether the service succeeded
string  message          # Success/failure reason
float64 rpms             # Average RPMs over the test run
float64 speed_m_per_s    # Speed in meters/second
